# Generated by Django 4.2 on 2023-04-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='nombreArticulo',
            new_name='nombre',
        ),
    ]
